### ISSUE TITLE
Hire > API > CRUD canditates

### ISSUE THREAD

**Issue by danlex** [remote-labs-sarl/hire-backend#2]
- [x] endpoint /candidate
- [x] create
  - [x] entity
- [x] read
   - [ ] pagination page, size
   - [ ] keywords
- [x] update
  - [x] id, entity
- [x] delete
  - [x] id
- [x] authentication
  - [x] 403 unauthorized

Candidate entity
@EngineerELdorado

**Comment by EngineerELdorado** [comment]
Done... pending frontend now

**Comment by EngineerELdorado** [comment]
Done... pending frontend now
